// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwjsd2nucJl-aibi4iCZkZ_edp7_SFBKs',
    appId: '1:613732719339:web:a4ec8e3efb120ce84f7cae',
    messagingSenderId: '613732719339',
    projectId: 'chat-ncst',
    authDomain: 'chat-ncst.firebaseapp.com',
    storageBucket: 'chat-ncst.appspot.com',
    measurementId: 'G-NFDV0SQPTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXAZ5uiP9QQB5skNm_koEs_dkeniSvKWE',
    appId: '1:613732719339:android:b88d18a6597262f94f7cae',
    messagingSenderId: '613732719339',
    projectId: 'chat-ncst',
    storageBucket: 'chat-ncst.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsZyRXYYx1HgY0lviENXD-S3-WjN_e59o',
    appId: '1:613732719339:ios:6c6e557ad069bc294f7cae',
    messagingSenderId: '613732719339',
    projectId: 'chat-ncst',
    storageBucket: 'chat-ncst.appspot.com',
    iosClientId: '613732719339-5qqc4e8c8rros93mdg7qqoak4gsis9b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatNcst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsZyRXYYx1HgY0lviENXD-S3-WjN_e59o',
    appId: '1:613732719339:ios:6c6e557ad069bc294f7cae',
    messagingSenderId: '613732719339',
    projectId: 'chat-ncst',
    storageBucket: 'chat-ncst.appspot.com',
    iosClientId: '613732719339-5qqc4e8c8rros93mdg7qqoak4gsis9b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatNcst',
  );
}
